[package]
name    = "{{demo}}"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]
edition = "2018"

[dependencies]
rand       = { version = "0.7", features = [ "stdweb" ] }
num-traits = "0.2"
Inflector = "0.11"
nalgebra   = "0.19"
ncollide2d = "0.21"
kiss3d     = "0.22"
nphysics2d = "0.13"
nphysics_testbed2d = { version = "0.7", features = [ "fluids" ] }
salva2d = { version = "0.1", features = [ "nphysics" ] }
stdweb = "0.4"

[profile.release]
lto = true
codegen-units = 1

[[bin]]
name = "{{demo}}"
path = "./{{demo}}.rs"
